#
# Makefile for the input misc drivers.
#

# Each configuration option enables a list of files.

#obj-$(CONFIG_INPUT_SX9323)		+= sx9323.o

ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include

obj-y	+= sx9323.o

