#
# Makefile for misc devices that really don't fit anywhere else.
#

#DTS2017010401865  xingbin/xwx427571 20170104 begin
obj-y += NT51021_WSVGA_DSI_VDO_INNOLUX.o
#DTS2017010401865  xingbin/xwx427571 20170104 end
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
