ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/FT3427/include/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/FT3427/include/$(CONFIG_FT3327_FIRMWARE)/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/

obj-y +=  focaltech_ex_fun.o
obj-y +=  focaltech_flash.o
obj-y +=  focaltech_core.o
obj-y +=  focaltech_test.o


